version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: dotnet restore
before_build:
- ps: |
    $xmlPath = "$env:appveyor_build_folder\CoreLibJune17\CoreLibJune17.csproj"
    $xml = [xml](get-content $xmlPath)
    $propertyGroup = $xml.Project.PropertyGroup | Where { $_.Version}
    $propertyGroup.Version = $env:appveyor_build_version
    $xml.Save($xmlPath)
build:
  verbosity: minimal
after_build:
- msbuild %appveyor_build_folder%\CoreLibJune17\CoreLibJune17.csproj /t:pack
artifacts:
- path: '**\*.nupkg'
